### ISSUE TITLE
not support in nuxt3 

### ISSUE THREAD

**Issue by liuchangfitcloud** [vueComponent/ant-design-vue-nuxt#10]
A message is displayed indicating that the language package cannot be imported.
Mac pro 2021 M1 node-v18.3 pnpm 7 
<img width="1082" alt="image" src="https://github.com/vueComponent/ant-design-vue-nuxt/assets/44662176/4ea12404-d60b-4b83-8638-b8a6e4400a4e">
<img width="605" alt="image" src="https://github.com/vueComponent/ant-design-vue-nuxt/assets/44662176/9362302a-a5f1-4e1a-939a-5416088789cc">

**Comment by liuchangfitcloud** [comment]
`{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build --dotenv .env.production",
    "dev": "nuxt dev --dotenv .env.development",
    "generate": "nuxt generate --dotenv .env.production",
    "preview": "nuxt preview --dotenv .env.production",
    "postinstall": "nuxt prepare --dotenv .env.production",
    "lint": "eslint --ext .ts,.js,.vue . --fix"
  },
  "devDependencies": {
    "@ant-design-vue/nuxt": "^1.0.1",
    "@ant-design/icons-vue": "^6.1.0",
    "@headlessui/vue": "^1.7.14",
    "@heroicons/vue": "^2.0.18",
    "@nuxt/devtools": "latest",
    "@nuxtjs/eslint-config-typescript": "^12.0.0",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@types/node": "^18.17.0",
    "eslint": "^8.45.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^5.0.0",
    "nuxt": "^3.6.5",
    "nuxt-icon": "^0.4.2",
    "prettier": "^3.0.0",
    "sass": "^1.64.1",
    "typescript": "^5.1.6",
    "vite-plugin-eslint": "^1.8.1"
  }
}
`

**Comment by aibayanyu20** [comment]
try this [demo](https://github.com/antdv-pro/antdv-nuxt-starter)
or need reproduce

**Comment by aibayanyu20** [comment]
update v1.1.0
