### ISSUE TITLE
刷新页面加载css慢一步

### ISSUE THREAD

**Issue by Panyoujies** [vueComponent/ant-design-vue-nuxt#15]
更新到"@ant-design-vue/nuxt": "^1.1.1"  刷新页面css加载还是慢一步。测试无效

**Comment by 7836246** [comment]
是的 解决了个寂寞 提供的demo也没有更正过来 https://github.com/antdv-pro/antdv-nuxt-starter

**Comment by 7836246** [comment]
![image](https://github.com/vueComponent/ant-design-vue-nuxt/assets/65436665/a928abfe-05cd-43f2-b61f-62c42683ffd9)

**Comment by aibayanyu20** [comment]
<img width="1663" alt="image" src="https://github.com/vueComponent/ant-design-vue-nuxt/assets/45655660/30fca23d-a0a8-4809-80d7-a97f9cb4de9c">
我这没问题呢

**Comment by aibayanyu20** [comment]
> 更新到"@ant-design-vue/nuxt": "^1.1.1" 刷新页面css加载还是慢一步。测试无效

参考文档[ssr-extract-style](https://antdv.com/docs/vue/ssr-extract-ssr-cn)

**Comment by Panyoujies** [comment]
> > 更新到"@ant-design-vue/nuxt": "^1.1.1" 刷新页面css加载还是慢一步。测试无效
> 
> 不是说安装了插件就可以自动加载样式了，如果想要刷新页面css加载同步，需要自己按自己的需求导出对应的样式css文件
> 
> 参考文档[ssr-extract-style](https://antdv.com/docs/vue/ssr-extract-ssr-cn)

这个我看不懂，在nuxt3 中怎么使用呢

**Comment by aibayanyu20** [comment]
https://github.com/antdv-pro/antdv-nuxt-starter/blob/main/scripts/genAntdStyle.ts

**Comment by 7836246** [comment]
> https://github.com/antdv-pro/antdv-nuxt-starter/blob/main/scripts/genAntdStyle.ts

我就是运行你的demo 强制刷新 就是会从默认按钮 在加载出来

**Comment by 7836246** [comment]
> > https://github.com/antdv-pro/antdv-nuxt-starter/blob/main/scripts/genAntdStyle.ts
> 
> 我就是运行你的demo 强制刷新 就是会从默认按钮 在加载出来

pnpm build pnpm start 运行的 样式还是和以前一样 pnpm run dev 根本运行不了

**Comment by aibayanyu20** [comment]
[在线测试](https://antdv-nuxt-starter.vercel.app/)

**Comment by 7836246** [comment]
> [在线测试](https://antdv-nuxt-starter.vercel.app/) build忘记调整了，可以再试一下，dev是因为nuxt的问题，这个后面处理一下

是的 可以了 我还有一个疑问 我发现是NaiveUi的那种 style全部在页面 在Nuxt配置加上     experimental: {
        inlineSSRStyles: false,
    }, 能否全部成link 这样可以查看源代码方便于维护

**Comment by Panyoujies** [comment]
> [在线测试](https://antdv-nuxt-starter.vercel.app/) build忘记调整了，可以再试一下，dev是因为nuxt的问题，这个后面处理一下

是可以了，，但还是有点麻烦

**Comment by aibayanyu20** [comment]
> > [在线测试](https://antdv-nuxt-starter.vercel.app/) build忘记调整了，可以再试一下，dev是因为nuxt的问题，这个后面处理一下
> 
> 是的 可以了 我还有一个疑问 我发现是NaiveUi的那种 style全部在页面 在Nuxt配置加上 experimental: { inlineSSRStyles: false, }, 能否全部成link 这样可以查看源代码方便于维护

这个后续研究一下吧

**Comment by selvinzr** [comment]
> > > [在线测试](https://antdv-nuxt-starter.vercel.app/) build忘记调整了，可以再试一下，dev是因为nuxt的问题，这个后面处理一下
> > 
> > 
> > 是的 可以了 我还有一个疑问 我发现是NaiveUi的那种 style全部在页面 在Nuxt配置加上 experimental: { inlineSSRStyles: false, }, 能否全部成link 这样可以查看源代码方便于维护
> 
> 这个后续研究一下吧

引入了静态的css，但是似乎没有办法关闭内联样式的渲染，严重冗余
