### ISSUE TITLE
Component PortalWrapper is missing template or render function

### ISSUE THREAD

**Issue by Kundakchan** [vueComponent/ant-design-vue-nuxt#16]
In the nuxt 3 project, I added the Ant-Design-Vue module
`nuxt.config.ts`
```
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    '@ant-design-vue/nuxt'
  ],
  css: ['~/assets/styles/main.scss']
})
```
Adding a component `<a-dropdown>` in the project and in the browser, after updating the page, it gives an error `(индекс):1     GET http://localhost:3000/ 500 (Internal Server Error)`

![5VXq0](https://github.com/vueComponent/ant-design-vue-nuxt/assets/43012466/edaf6922-d7fd-4034-91e3-5676d97ffcd6)

there is an error in the terminal console: `[Vue warn]: Component PortalWrapper is missing template or render function.`

![ZJHWA](https://github.com/vueComponent/ant-design-vue-nuxt/assets/43012466/951c0160-7011-4266-9ed7-1f358018cdf8)

Component code:

```
<script lang="ts" setup>
import { UserOutlined } from '@ant-design/icons-vue'

// Types
import type { ItemType } from 'ant-design-vue'

const items: ItemType[] = reactive([
  {
    key: 'Profile',
    label: 'Настройка профиля',
    onClick: () => {
      console.log(this)
    }
  },
  {
    key: 'LogOut',
    label: 'Выйти',
    onClick: () => {
      console.log(this)
    }
  }
])

</script>

<template>
  <a-dropdown>
    <a-button :shape="'circle'" :type="'primary'" :size="'large'" :icon="h(UserOutlined)"></a-button>
    <template #overlay>
      <h1>menu</h1>
      <a-menu
        :items="items"
      />
    </template>
  </a-dropdown>
</template>
```
Can anyone tell me why this is happening and how to fix it ?

**Comment by aibayanyu20** [comment]
Try downgrading @ant-design/icons-vue to 6.1.0

**Comment by aibayanyu20** [comment]
update 1.1.2
