### ISSUE TITLE
ant-design-vue/nuxt 自动引入的组件没有引入对应的 typing 吗？

### ISSUE THREAD

**Issue by Logosww** [vueComponent/ant-design-vue-nuxt#19]
![image](https://github.com/vueComponent/ant-design-vue-nuxt/assets/87473526/f2bf0d4e-59ff-46df-8a00-4fc3ecf3d201)
起码 Volar 不能正确的在模板中提供组件的类型。

**Comment by aibayanyu20** [comment]
这应该是主库类型的问题

**Comment by nailiable** [comment]
首次安装我也没有typing；只要试试命令面板重启一下TS和Volar服务器就行。

<img width="473" alt="image" src="https://github.com/vueComponent/ant-design-vue-nuxt/assets/166735097/e9d04093-3503-4d55-961b-a293d5fd49bd">

<img width="731" alt="image" src="https://github.com/vueComponent/ant-design-vue-nuxt/assets/166735097/99655ab3-1d2e-47d5-9faf-2cf896a5a62d">
