### ISSUE TITLE
我看文档里 SSR 静态样式导出的介绍，只有全量导出的方案，像 antd of react 官网上的按需导出方案，在 Nuxt 中应该怎么写？

### ISSUE THREAD

**Issue by Logosww** [vueComponent/ant-design-vue-nuxt#20]
求教

**Comment by Logosww** [comment]
主要是我不知道要到哪个生命周期钩子里去预渲染一遍页面来获取 style cache 比较合适...想着既然是抽离样式按需导出的话，最好应该在 building 阶段完成，但 building 的时候又怎么去 renderToString 呢？

**Comment by aibayanyu20** [comment]
目前没什么好方案，欢迎来PR

**Comment by markthree** [comment]
我简单实现了一个 demo，你可以看看，按需生成 → [nuxt-antd-css-demo/tree/demand](https://github.com/markthree/nuxt-antd-css-demo/tree/demand)。

如果可以，我想我可以提一个 pr 来迁移用到的组件，同时在 README 中加以说明。

**Comment by aibayanyu20** [comment]
> 我简单实现了一个 demo，感兴趣可以看看，按需生成 → [nuxt-antd-css-demo/tree/demand](https://github.com/markthree/nuxt-antd-css-demo/tree/demand?rgh-link-date=2024-01-09T10%3A32%3A09Z)。
> 
> 如果可以，我想我可以提一个 pr 来迁移用到的组件，同时在 README 中加以说明。
> 
> 核心用到的组件 → [nuxt-antd-css-demo/blob/demand/components/AExtractStyle.vue](https://github.com/markthree/nuxt-antd-css-demo/blob/demand/components/AExtractStyle.vue?rgh-link-date=2024-01-09T10%3A32%3A09Z)

@markthree 可以提交一个PR过来，nuxt3用到的都是esm模式，所以建议使用esm来测试，目前antdvnuxt插件也是仅输出es包，尽可能的保持一致性

**Comment by aibayanyu20** [comment]
update 1.4.1
