### ISSUE TITLE
Changing locale for dayjs

### ISSUE THREAD

**Issue by Djaangoo** [vueComponent/ant-design-vue-nuxt#22]
Hi, how can i change dayjs locale dynamicly in Ant Design like in link below? 
[demo](https://codesandbox.io/s/ant-design-vue-4-0-6-forked-46vyw4?file=/src/demo.vue)

**Comment by aibayanyu20** [comment]
Can you provide a reproducible demo based on nuxt3? Thanks！[online playground](https://stackblitz.com/~/github.com/antdv-pro/antdv-nuxt-starter )
