### ISSUE TITLE
使用ant-design-vue-nuxt后，点击按钮会报错

### ISSUE THREAD

**Issue by cdooow** [vueComponent/ant-design-vue-nuxt#24]
点击按钮后，控制台会报错
![QQ截图20231115182639](https://github.com/vueComponent/ant-design-vue-nuxt/assets/43906868/99ac24db-ab1a-48bb-ae38-185aa1c77900)

**Comment by aibayanyu20** [comment]
这可能是个bug，不过你可以尝试在button的外面包一层a-config-provider或许能帮助你解决这个错误
