### ISSUE TITLE
CSS Delay

### ISSUE THREAD

**Issue by azaryahuu** [vueComponent/ant-design-vue-nuxt#25]
When reloading a page antd css has a delay which results to a bad ux behavior

**Comment by aibayanyu20** [comment]
You can view the solution here https://github.com/vueComponent/ant-design-vue-nuxt/issues/6

**Comment by fskarmeta** [comment]
any news about this with dark theme token :( ?  ❤️

**Comment by aibayanyu20** [comment]
try this demo https://github.com/antdv-community/antdv-nuxt-starter 

[click show preview](https://antdv-nuxt-starter.vercel.app/)

**Comment by fskarmeta** [comment]
thanks @aibayanyu20 , i i'm trying to also add a custom token but then the same issue appears, maybe algorithm dark and custom token don't go well together.

**Comment by aibayanyu20** [comment]
> thanks @aibayanyu20 , i i'm trying to also add a custom token but then the same issue appears, maybe algorithm dark and custom token don't go well together.

try replace ant-design-vue version to "ant-design-vue": "npm:@antd-tiny-vue/test@^4.0.7"

```json
{
	"ant-design-vue": "npm:@antd-tiny-vue/test@^4.0.7"
}
```

may be resolve problem

**Comment by fskarmeta** [comment]
> > thanks @aibayanyu20 , i i'm trying to also add a custom token but then the same issue appears, maybe algorithm dark and custom token don't go well together.
> 
> try replace ant-design-vue version to "ant-design-vue": "npm:@antd-tiny-vue/test@^4.0.7"
> 
> ```json
> {
> 	"ant-design-vue": "npm:@antd-tiny-vue/test@^4.0.7"
> }
> ```
> 
> may be resolve problem

hey @aibayanyu20 , happy holidays ! 

I tried this one but no luck sadly. But also I never had `ant-design-vue` explicitly installed since it's exposed by your library, you mean overriding it ?  Thanks for the help.

**Comment by aibayanyu20** [comment]
> > > thanks @aibayanyu20 , i i'm trying to also add a custom token but then the same issue appears, maybe algorithm dark and custom token don't go well together.
> > 
> > 
> > try replace ant-design-vue version to "ant-design-vue": "npm:@antd-tiny-vue/test@^4.0.7"
> > ```json
> > {
> > 	"ant-design-vue": "npm:@antd-tiny-vue/test@^4.0.7"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > may be resolve problem
> 
> hey @aibayanyu20 , happy holidays !
> 
> I tried this one but no luck sadly. But also I never had `ant-design-vue` explicitly installed since it's exposed by your library, you mean overriding it ? Thanks for the help.

update ant-design-vue@4.0.8

**Comment by fskarmeta** [comment]
sadly the problem still persists :'(
