### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by ezewu** [vueComponent/ant-design-vue-nuxt#28]
"nuxt": "^3.8.2"
    "@ant-design-vue/nuxt": "^1.2.0"

app.vue里面添加
``` vue
<script lang="ts" setup>
const handleMessage = () => {
  message.info("This is a normal message");
};
</script>
<template>
  <a-button @click="handleMessage"> button </a-button>
</template>
```
点击按钮时，控制台会报一个错
<img width="1012" alt="image" src="https://github.com/vueComponent/ant-design-vue-nuxt/assets/22029449/4ad296e2-1475-4ca6-8923-33bed5185080">

**Comment by aibayanyu20** [comment]
包裹一层config-provider试一下

**Comment by aibayanyu20** [comment]
update 4.0.8

**Comment by ezewu** [comment]
感谢
