### ISSUE TITLE
打包后样式丢失

### ISSUE THREAD

**Issue by wen403** [vueComponent/ant-design-vue-nuxt#29]
![image](https://github.com/vueComponent/ant-design-vue-nuxt/assets/67454874/6414c232-abee-4738-aa5c-4f9322bfaa2e)
![image](https://github.com/vueComponent/ant-design-vue-nuxt/assets/67454874/ff1ed1c5-34f6-4544-8c13-fb382dacb210)

**Comment by aibayanyu20** [comment]
尝试加一个crosse-env 配置一下NODE_ENV=production

**Comment by wen403** [comment]
感谢你的回答，可惜还是没有任何效果
这是一个复现地址：`https://stackblitz.com/github/wen403/nigi-pro?file=layouts%2Fdefault.vue`
![image](https://github.com/vueComponent/ant-design-vue-nuxt/assets/67454874/76775934-bb44-490b-8e3b-c0168e32b7fc)

**Comment by aibayanyu20** [comment]
![image](https://github.com/vueComponent/ant-design-vue-nuxt/assets/45655660/9eaa156c-445c-45b3-8816-bc1a5b036f08)
你用了两个不同的实例，应该是造成这个原因的根本因素，如果你用es就都用es。lib就都用lib，确保是一个实例

**Comment by wen403** [comment]
### 外面的样式正确了，里面组件的样式又没用了
![image](https://github.com/vueComponent/ant-design-vue-nuxt/assets/67454874/ecc8b295-083c-46f9-ab70-fac3844d5b69)
![image](https://github.com/vueComponent/ant-design-vue-nuxt/assets/67454874/c519ea97-97eb-4c39-8f8c-696be388661b)

**Comment by aibayanyu20** [comment]
组件默认使用es，建议全用es模式，参考我们提供的demo https://github.com/antdv-community/antdv-nuxt-starter

**Comment by wen403** [comment]
感谢你的回答 @aibayanyu20
