### ISSUE TITLE
补全css样式

### ISSUE THREAD

**Issue by catiz** [vueComponent/ant-design-vue-nuxt#4]
nuxt.config.ts
```typescript
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ["@ant-design-vue/nuxt"],
  css: [
    'ant-design-vue/dist/antd.css'
  ],
})
```

**Comment by aibayanyu20** [comment]
目前插件基于ant-design-vue@4版本开发的没有支持4以下的版本，如果有需要可以提PR支持

**Comment by selvinzr** [comment]
> 目前插件基于ant-design-vue@4版本开发的没有支持4以下的版本，如果有需要可以提PR支持
缺少对于ssr的支持，很多组件需要client only

**Comment by aibayanyu20** [comment]
> > 目前插件基于ant-design-vue@4版本开发的没有支持4以下的版本，如果有需要可以提PR支持
> > 缺少对于ssr的支持，很多组件需要client only

对SSR支持不好的组件缺失需要套用client only
