### ISSUE TITLE
 Pre-transform error: Failed to resolve import "ant-design-vue/es" from "virtual:nuxt:D:\project\git\\.nuxt\imports.mjs". Does the file e xist?

### ISSUE THREAD

**Issue by bbhxwl** [vueComponent/ant-design-vue-nuxt#40]
![image](https://github.com/vueComponent/ant-design-vue-nuxt/assets/26525599/035f4036-67a3-43bf-862b-9b157efd9cda)

**Comment by xiaozhu2024** [comment]
I can help you by providing a reproduction

**Comment by aibayanyu20** [comment]
I can help you by providing a reproduction

**Comment by bbhxwl** [comment]
> I can help you by providing a reproduction

![image](https://github.com/vueComponent/ant-design-vue-nuxt/assets/26525599/ee1aa75c-ca90-425f-97c3-fb2b87f630dc)

**Comment by aibayanyu20** [comment]
you should install ant-design-vue & @ant-design/icons-vue

**Comment by sailor103** [comment]
遇到同样的问题，请问解决了吗？
