### ISSUE TITLE
dayjs error not provide an export named 'default'

### ISSUE THREAD

**Issue by bobby169** [vueComponent/ant-design-vue-nuxt#44]
> client.mjs:30 SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/dayjs@1.11.10/node_modules/dayjs/plugin/advancedFormat.js?v=45ac0268' does not provide an export named 'default' (at dayjs.js?v=45ac0268:7:8)

The above error is reported, dayjs needs to set tsconfig.json
```
{ //tsconfig.json
  "compilerOptions": {
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
  }
}
```

**Comment by markthree** [comment]
The same solution → https://github.com/nuxt/nuxt/issues/26007#issuecomment-1970330058
