### ISSUE TITLE
Failed to resolve component: a-extract-style

### ISSUE THREAD

**Issue by avxkim** [vueComponent/ant-design-vue-nuxt#47]
Code:

```
  <a-extract-style>
    <a-textarea placeholder="text field" />
  </a-extract-style>
```

causing Nuxt 3 error:

"[Vue warn]: Failed to resolve component: a-extract-style
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement."

Nuxt 3
```
    "@ant-design-vue/nuxt": "^1.4.1",
    "nuxt": "^3.6.2",
```

**Comment by sabasayer** [comment]
Hi, if you are still looking make sure ssr is on because this only works on SSR. [Check the code](https://github.com/vueComponent/ant-design-vue-nuxt/blob/31c4f66040b5e033c64320cef832d1c8d17df0d6/src/module.ts#L33)
