### ISSUE TITLE
Why Not Fork?

### ISSUE THREAD

**Issue by sxzz** [vueComponent/ant-design-vue-nuxt#5]
There are many similarities between https://github.com/element-plus/element-plus-nuxt and the repository (https://github.com/vueComponent/ant-design-vue-nuxt/tree/f52e16b2bdbe506117ea67d1350b15e74ad60032).

https://github.com/search?q=nuxt.options.build.transpile.push%28libraryName%29&type=code
After searching a small code snippet from this repository throughout the entire GitHub codebase, I found that only three repositories share the same code. These are Nuxt plugins of Element Plus, Vant (which has the same author as Element Plus), and this repository. Even "Element Plus" is mentioned in the `README.md` of this repo.

Therefore, why not fork it directly?

---

Additionally, the repository is missing a license file. Please follow the MIT license, which only require the preservation of copyright and license notices, if this repo used code from https://github.com/element-plus/element-plus-nuxt. Thanks.

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

**Comment by aibayanyu20** [comment]
项目确实参考了elementplus的部分代码结构，非常抱歉，由于我个人问题没有对代码进行审查，目前已添加license，保留了element-plus的信息。
