### ISSUE TITLE
 The requested module '/_nuxt/node_modules/.pnpm/dayjs@1.11.10/node_modules/dayjs/plugin/advancedFormat.js?v=3a277238' does not provide an export named 'default' (at dayjs.js?v=3a277238:7:8)

### ISSUE THREAD

**Issue by wangjialuo** [vueComponent/ant-design-vue-nuxt#53]
The requested module '/_nuxt/node_modules/.pnpm/dayjs@1.11.10/node_modules/dayjs/plugin/advancedFormat.js?v=3a277238' does not provide an export named 'default' (at dayjs.js?v=3a277238:7:8)

**Comment by ikraddy** [comment]
遇到了一样的问题。

**Comment by aibayanyu20** [comment]
"dayjs/plugin/advancedFormat.js" replace "dayjs/esm/plugin/advancedFormat"

**Comment by ikraddy** [comment]
> "dayjs/plugin/advancedFormat.js" replace "dayjs/esm/plugin/advancedFormat"

在哪里替换

**Comment by qianyingchao** [comment]
> 遇到了一样的问题。

刚也遇到，然后直接把ant-design-vue添加进依赖

**Comment by ikraddy** [comment]
> > 遇到了一样的问题。
> 
> 刚也遇到，然后直接把ant-design-vue添加进依赖

亲，可以贴一下你的代码不

**Comment by tommylao** [comment]
> > > 遇到了一样的问题。
> > 
> > 
> > 刚也遇到，然后直接把ant-design-vue添加进依赖
> 
> 亲，可以贴一下你的代码不

再安裝 ant-design-vue 到依賴，就解決問題。
