### ISSUE TITLE
Nuxt with AntDV Throws Error: yarn and pnpm

### ISSUE THREAD

**Issue by LireEruel** [vueComponent/ant-design-vue-nuxt#57]
I followed the settings using the link below:

https://nuxt.com/modules/ant-design-vue

## 1.  pnpm add -D @ant-design-vue/nuxt
![image](https://github.com/vueComponent/ant-design-vue-nuxt/assets/47496422/4321564d-0995-4cf6-80bb-38d6b06f7e19)
## 2. Add `@ant-design-vue/nuxt` to the `modules` section of `nuxt.config.ts`
my nuxt.config.ts
```
export default defineNuxtConfig({
  modules: ["@ant-design-vue/nuxt"],
  devtools: { enabled: true },
});
```
## 3. App.vue
```
<script lang="ts" setup>
const handleMessage = () => {
  message.info("This is a normal message");
};
</script>
<template>
  <a-button @click="handleMessage"> button </a-button>
</template>
```
## 4. result

![image](https://github.com/vueComponent/ant-design-vue-nuxt/assets/47496422/f28a23ca-3538-4065-b7bf-1bce1077ad15)

![image](https://github.com/vueComponent/ant-design-vue-nuxt/assets/47496422/52ea0020-a275-4655-9de9-91785447ade6)
![image](https://github.com/vueComponent/ant-design-vue-nuxt/assets/47496422/95c7ef8a-6db0-4ffe-9b66-77d6e2d79e40)

## Attempts to Resolve the Issue

1. Reinstalling Dayjs
- Not working
2. Changed the Package Manager  pnpm to npm
- Worked!
- yarn, pnpm is not working. only npm is working

**Comment by LireEruel** [comment]
After deleting the node_modules and reinstalling with npm, it worked properly. I am curious as to why this issue occurs. Since the version management tools preferred by modern developers are yarn and pnpm rather than npm, I will keep the issue open.

**Comment by aibayanyu20** [comment]
try  `npx nuxi@latest module add ant-design-vue`

**Comment by LireEruel** [comment]
Thank you!!!
