### ISSUE TITLE
性能过差

### ISSUE THREAD

**Issue by Sun-ZhenXing** [vueComponent/ant-design-vue-nuxt#63]
测试最新版本 1.4.2，无论是否使用 `icons: false`，所有图标都会全部加载，所有组件也会全部加载一遍，导致开发时首页加载几分钟也加载不出来。

如何让自动导入能按需导入呢？

**Comment by aibayanyu20** [comment]
可以提供一个复现的demo，我测试了一下没遇到这个问题

**Comment by drwpls** [comment]
Encounter this today, used with Bun.
The app try to load all of components styles from nitro leading poor performance.

**Comment by n0099** [comment]
#66
