### ISSUE TITLE
dayjs报错

### ISSUE THREAD

**Issue by XIZS** [vueComponent/ant-design-vue-nuxt#64]
使用pnpm安装依赖
新建最新nuxt项目,项目改为ssr:false.
直接npx nuxi@latest module add ant-design-vue,然后app.vue中添加a-button,运行后加载3000+个的请求,然后报以下错误

Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/dayjs@1.11.13/node_modules/dayjs/plugin/advancedFormat.js?v=9a5b1fed' does not provide an export named 'default' (at dayjs.js?v=9a5b1fed:7:8)

**Comment by DoloreMentale** [comment]
+1, it breaks app in dev/prod mode

**Comment by vanchinh1989** [comment]
+1, I also don't know how to do it now, the app uses too many ant controls. please fix it

**Comment by A-Hao-Cheng** [comment]
+1 The requested module '/_nuxt/node_modules/dayjs/plugin/advancedFormat.js?v=8fbf2740' does not provide an export named 'default'

**Comment by DoloreMentale** [comment]
It seems there is an issue with module imports and auto imports in nuxt itself with this library.

As a workaround for dayjs and error _The requested module advancedFormat does not provide an export named 'default'_
you can add alias for dayjs esm in nuxt.config like that:
```
// nuxt.config.ts
export default defineNuxtConfig({
 alias: {
    dayjs: "dayjs/esm",
  },
})
```
It should solve dayjs import issue, but its not the end :(
If you are using nuxt auto imports and icons from this library, you will get the same error, but with icons import. The only way (at least working) is to explicitly import icons from @ant-design/icons-vue

**Comment by aibayanyu20** [comment]
update @ant-design-vue/nuxt@1.4.3
