### ISSUE TITLE
加载到许多没用到的组件，影响开发下加载速度

### ISSUE THREAD

**Issue by ponjs** [vueComponent/ant-design-vue-nuxt#68]
例如页面这里页面只有一个 `Button` 组件，但是会加载所有组件的资源

👉[在线Demo](https://stackblitz.com/edit/nuxt-starter-ts5tgm?file=app.vue)

![image](https://github.com/user-attachments/assets/a8d19424-7b57-4f7a-b8ff-746654ccb8c0)

**Comment by xuanhen2013** [comment]
`nuxt.config.ts` 增加配置
```js
  vite: {
    resolve: {
      alias: {
        'ant-design-vue/es': 'ant-design-vue/es',
      },
    },
  },
  ```

**Comment by aibayanyu20** [comment]
update 1.4.6
