### ISSUE TITLE
Failed to resolve import "ant-design-vue/dist/antd.css"

### ISSUE THREAD

**Issue by algoriq** [vueComponent/ant-design-vue-nuxt#70]
"@ant-design-vue/nuxt": "^1.4.5",
"ant-design-vue": "^4.2.5",

nuxt.config.ts

`
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  modules: [
    '@ant-design-vue/nuxt',
  ],
  ssr: false,
  css: [
    'ant-design-vue/dist/antd.css',
    '~/app.scss',
  ],
  antd: {},
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          // This will hide the warning message from console.
          // https://sass-lang.com/documentation/breaking-changes/legacy-js-api/
          silenceDeprecations: ['legacy-js-api'],
        },
      },
    },
  },
})
`

**Comment by xuanhen2013** [comment]
`version ` 
 `1.4.5` -> `1.4.4`

**sorrry**

**Comment by algoriq** [comment]
@xuanhen2013 Are there any plans to fix this issue or are there any workarounds?

**Comment by xuanhen2013** [comment]
> @xuanhen2013 Are there any plans to fix this issue or are there any workarounds?

It has been merged but not yet released.

**Comment by algoriq** [comment]
@xuanhen2013 ok, thanks.

**Comment by aibayanyu20** [comment]
1.4.6
