### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by BillEliot** [vueComponent/ant-design-vue-nuxt#8]
依然是
document is not defined

**Comment by aibayanyu20** [comment]
可以尝试跑一下我们的demo[antdv-nuxt-starter](https://github.com/antdv-pro/antdv-nuxt-starter)

**Comment by m1xui** [comment]
我使用Modal组件就会报document is not defined错误，除非我用`<ClientOnly>`包裹它。[antdv-nuxt-starter](https://github.com/antdv-pro/antdv-nuxt-starter)也存在相同的问题

**Comment by aibayanyu20** [comment]
现在很多组件是避免不了嵌套ClientOnly的，像Tour、Modal、Drawer这种里面都是使用了document
