### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yzlhdy** [vueComponent/ant-design-vue-nuxt#9]
使用最新版报错
  Internal server error: Failed to resolve import "ant-design-vue/es" from "pages\about.vue". Does the file exist?                    13:54:27

                                                                                                                                            13:54:50

 ERROR  Internal server error: Failed to resolve import "ant-design-vue/es" from "pages\about.vue". Does the file exist?  
![image](https://github.com/vueComponent/ant-design-vue-nuxt/assets/49674055/8cf31591-9cd6-415f-9a56-295db6162251)

**Comment by yzlhdy** [comment]
![image](https://github.com/vueComponent/ant-design-vue-nuxt/assets/49674055/5bcf0a9b-45d8-4d53-a54f-50ba1400a431)

**Comment by aibayanyu20** [comment]
get，发一下你的系统版本和node版本

**Comment by WhitePaper233** [comment]
`yarn add ant-design-vue` 即可

**Comment by aibayanyu20** [comment]
update v1.1.0
